Michel #17
INF1-B/and-action pull request #20
Opened 2021-12-01 09:49 UTC by NHL-Michel

2021-12-01 11:27 UTC, Mappeldorn requested changes

2021-12-01 11:27 UTC, Mappeldorn commented on public/director-movie-specific.php
> +          <button class="delete-movie" type="submit" name="delete-movie"> Delete This movie </button>
Is het niet handiger op gewoon een <a> te gebruiken, dit is ook makkelijker te stylen. En je hebt dan ook geen form nodig want de url kan dan naar delete_movie.php waar die word verwijdert.

De styling komt ook niet helemaal overeen met het ontwerp
![afbeelding](https://user-images.githubusercontent.com/37366890/144226587-4c47f181-39fb-41fa-b82b-546a78926106.png)

2021-12-01 11:29 UTC, Mappeldorn commented on public/director-movie-specific.php
> +          <button class="delete-movie" type="submit" name="delete-movie"> Delete This movie </button>
kleur is #DC3545

2021-12-01 12:25 UTC, Mappeldorn approved these changes

2021-12-02 13:29 UTC, Hajo300 approved these changes

2021-12-02 20:08 UTC, merged