login, signup
INF1-B/and-action pull request #24
Opened 2021-12-02 19:43 UTC by Moniquesbg

Login page, sign up page and sign up page for directors created

2021-12-02 20:15 UTC, Mappeldorn requested changes
Gebruik geen px bij width maar %. Want bij mij staat die niet helemaal in het midden.
![afbeelding](https://user-images.githubusercontent.com/37366890/144496023-99f9895e-1f09-457d-94cf-1f856367ea95.png)

2021-12-03 12:05 UTC, NHL-Michel requested changes
Naast de kleine puntjes, hetzelfde punt als wat max had aangegeven

2021-12-03 12:05 UTC, NHL-Michel commented on public/assets/css/login.css
> +font-family: Roboto;
indentje

2021-12-03 12:05 UTC, NHL-Michel commented on public/assets/css/login.css
> +
loze regel

2021-12-03 12:05 UTC, NHL-Michel commented on public/assets/css/login.css
> +
loze regel

2021-12-03 12:05 UTC, NHL-Michel commented on public/assets/css/signUp.css
> +font-family: Roboto;
indentje

2021-12-03 12:05 UTC, NHL-Michel commented on public/assets/css/signUp.css
> +
loze ruimte

2021-12-03 12:05 UTC, NHL-Michel commented on public/assets/css/signUpDirector.css
> +font-family: Roboto;
indentje

2021-12-03 12:15 UTC, Mappeldorn commented on public/assets/css/login.css
> +font-family: Roboto;
Deze kan ook weg, staat zelf ook al in style.css. wanneer dit gemerged word de font ook gelijk aangepast

2021-12-07 11:49 UTC, NHL-Michel approved these changes

2021-12-07 11:50 UTC, Mappeldorn approved these changes

2021-12-07 12:01 UTC, merged