Nikita #14
INF1-B/and-action pull request #25
Opened 2021-12-02 20:16 UTC by Noizeisdead

Disapprove page

2021-12-03 12:03 UTC, NHL-Michel requested changes
![image](https://user-images.githubusercontent.com/89914058/144599214-ede68e79-b6db-4154-89cc-aef5d22d409e.png)

Volgens mij zit er overlap tussen de klassenamen die je gebruikt (zie afbeelding) Ook gebruik je in de eigen stylesheet een zelfde klassenaam als in de algemene stylesheet, dit zou een andere benaming moeten hebben (de klassenaam .container heb je bijvoorbeeld ook gebruik in je eigen stylesheet)

2021-12-03 12:14 UTC, Mappeldorn requested changes

2021-12-03 12:14 UTC, Mappeldorn commented on public/assets/css/dissaprovePageStyle.css
> +    color: #F9B354;
Geef de a een class of zorg dat je alleen de a pakt die in je div staat. Nu pakt die ook de a in de header

2021-12-06 09:44 UTC, NHL-Michel approved these changes
Samen even gezeten, Volgens mij klopt het helemaal zo!

2021-12-06 14:25 UTC, Mappeldorn approved these changes

2021-12-06 15:28 UTC, merged