Nikita #7
INF1-B/and-action pull request #26
Opened 2021-12-02 20:17 UTC by Noizeisdead

Homepage when signed in

2021-12-03 10:45 UTC, NHL-Michel requested changes
2 kleine puntjes

2021-12-03 10:45 UTC, NHL-Michel commented on public/assets/homepageStyle.css
> +flex-direction: column;
indentje

2021-12-03 10:45 UTC, NHL-Michel commented on public/homepage.php
> +      <div></div>
is deze div nog nodig?

2021-12-03 10:45 UTC, NHL-Michel commented on public/homepage.php
> +      <div></div>
regel 125

2021-12-03 12:52 UTC, NHL-Michel approved these changes
Styling is goed zo! Dynamisch maken kan wat mij betreft wanneer we de database draaiende hebben

2021-12-06 14:21 UTC, NHL-Michel approved these changes

2021-12-06 14:26 UTC, Mappeldorn approved these changes

2021-12-06 15:28 UTC, merged