Serhan 10.1
INF1-B/and-action pull request #60
Opened 2021-12-13 12:43 UTC by serhangunes

2021-12-13 18:02 UTC, NHL-Michel requested changes

2021-12-13 18:02 UTC, NHL-Michel commented on public/assets/css/styleupload.css
> +    padding-left: 0;
Doet dit ook iets ? lijn 97

2021-12-13 18:02 UTC, NHL-Michel commented on public/director-upload-movie.php
> +                <label for="Sci-if" class="task"><input type="checkbox" name="Sci-if" id="Sci-if"> Sci-if</label>
spelfoutje, moet sci-fi zijn (science fiction)

2021-12-13 18:02 UTC, NHL-Michel commented on public/director-upload-movie.php
> +                <label for="Other" class="task"><input type="checkbox" name="Other" id="Other"> Other</label>
Op dit moment is het allemaal een unieke checkbox die je kan afvinken, maar komt het ook binnen als 13 aparte waardes. Zou je willen kijken of je dit ook nog kan verwerken naar een array? bijvoorbeeld door overal name="genre[]" neer te zetten.

`<input type="checkbox" name="genre[]" value="action"/>
<input type="checkbox" name="genre[]" value="comedy"/>
<input type="checkbox" name="genre[]" value="drama"/>
<input type="checkbox" name="genre[]" value="fantasy"/>
`

dit is ook een punt wat wel mist, de value

2021-12-14 07:06 UTC, Hajo300 commented on public/director-upload-movie.php
> +                <label for="Voilence" class="task"><input type="checkbox" name="Voilence" id="Voilence"> Voilence</label>
Violence *

2021-12-14 07:07 UTC, Hajo300 commented on public/director-upload-movie.php
> +                <label for="Foul-launguage" class="task"><input type="checkbox" name="Foul launguage" id="Foul-launguage"> Foul launguage</label>
language*

2021-12-14 07:08 UTC, Hajo300 commented on public/director-upload-movie.php
> +                <label for="Discrimnation" class="task"><input type="checkbox" name="Discrimnation" id="Discrimnation"> Discrimnation</label>
Discrimination *

2021-12-14 07:10 UTC, Hajo300 requested changes
Even goeie spellingscontrole door de code heen gooien

2021-12-14 07:48 UTC, Noizeisdead requested changes
Change title to and-action instead of template

2021-12-14 09:41 UTC, closed without merging