Monique #62
INF1-B/and-action pull request #66
Opened 2021-12-14 09:29 UTC by Moniquesbg

The logo in the header bigger and adjusted the admin approve page

2021-12-14 09:56 UTC, Hajo300 approved these changes

2021-12-14 14:53 UTC, NHL-Michel requested changes
Hey monique, erg netjes!

Enige puntje wat ik heb zijn de benamingen en het gebruik van de variabele in constants.php

Op dit moment gebruiken we geen constante variabele waardes in constants.php maar normale variabele waardes. 

Zou je dit nog even om willen zetten? Zie hier een stukje code met wat ik bedoel

`<?php
define("imageMimeTypes", [
  "image/jpeg",
  "image/png",
  "image/png"
]);
echo vehicles[0];		//car
?>`

Verder zou ik nog even in constants.php de benaming van de image waardes aanpassen naar 

imageMimeTypes
imageExtensions

Dan weten we dat het bedoeld wordt voor een afbeelding.

2021-12-15 10:00 UTC, Mappeldorn approved these changes

2021-12-15 12:15 UTC, NHL-Michel approved these changes

2021-12-15 12:17 UTC, merged