Serhan#39
INF1-B/and-action pull request #83
Opened 2021-12-23 14:37 UTC by serhangunes

forntend for change password and for user view movie

2021-12-23 18:15 UTC, NHL-Michel requested changes
@Hajo300 @Mappeldorn zouden jullie nog even willen kijken of video pagina zo is zoals jullie hem bedoelen (user-view-movie)? Volgens mij is de box te klein voor de video en moet de thumbnail van de video ook eruit.

2021-12-23 18:15 UTC, NHL-Michel commented on public/change-password.php
> +</head>
Serhan, in dit stuk tel ik meerdere malen de woorden 'register' en 'signing up'. Daarnaast ook code die uit gecomment is, waar je waarschijnlijk ook niks mee gaat doen. Het is goed dat je geen dubbel werk doet idd, maar pas het nog wel even aan naar de change-password pagina. 

Gaat voornamelijk om klasse namen, de titel van de pagina, de inhoud van de message op regel 9 etc.

2021-12-23 18:15 UTC, NHL-Michel commented on public/user-view-movie.php
> +            <iframe src="" title="placeholder" height="300" width="600"></iframe>
iframe? laat dit maar zo staan, alleen gebruiken we het video element, niet de iframe.

2021-12-24 12:04 UTC, Hajo300 requested changes
Inderdaad wat Michel zei. Video moet breder en de thumbnail moet weg.

2021-12-24 13:55 UTC, merged